version: '3'

volumes:
    postgres_data:
        driver: local

networks:
    postgres-network:
        driver: bridge

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django_application:
    container_name: tis
    image: tis
    ports:
        - "8000:8000"
    networks:
      - postgres-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db


